apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow
  namespace: keduit
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yellow
  template:
    metadata:
      labels:
        app: yellow
    spec:
      containers:
      - name: yellow
        image: chaewon0720/keduitlab:yellow
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
